#!/bin/bash
# We want to insert the ModalBottomSheet block right before the last closing brace of DetailsScreen, which is at line 371.
awk 'NR==370 {
print "    if (showBottomSheet) {"
print "        ModalBottomSheet("
print "            onDismissRequest = { showBottomSheet = false },"
print "            sheetState = sheetState,"
print "            containerColor = TrueBlack"
print "        ) {"
print "            Column("
print "                modifier = Modifier"
print "                    .fillMaxWidth()"
print "                    .padding(bottom = 32.dp)"
print "            ) {"
print "                if (uiState is DetailsUiState.Success && (uiState as DetailsUiState.Success).isInWatchlist) {"
print "                    Text("
print "                        text = \"تتم المشاهدة\","
print "                        color = TextPrimary,"
print "                        fontSize = 16.sp,"
print "                        fontWeight = FontWeight.Bold,"
print "                        modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)"
print "                    )"
print "                    HorizontalDivider("
print "                        color = GoldYellow,"
print "                        thickness = 2.dp,"
print "                        modifier = Modifier.padding(bottom = 8.dp)"
print "                    )"
print "                }"
print "                val menuItems = listOf("
print "                    Pair(\"تخصيص\", Icons.Default.Edit),"
print "                    Pair(\"مفضلة\", Icons.Default.FavoriteBorder),"
print "                    Pair(\"إضافة إلى قائمة\", Icons.Default.PlaylistAdd),"
print "                    Pair(\"شاهد لاحقًا\", Icons.Default.Schedule),"
print "                    Pair(\"إيقاف المشاهدة\", Icons.Default.Close),"
print "                    Pair(\"إزالة العرض\", Icons.Default.Remove),"
print "                    Pair(\"مشاركة\", Icons.Default.Share)"
print "                )"
print "                menuItems.forEach { (text, icon) ->"
print "                    Row("
print "                        modifier = Modifier"
print "                            .fillMaxWidth()"
print "                            .clickable {"
print "                                if (text == \"إزالة العرض\" && uiState is DetailsUiState.Success) {"
print "                                    val state = uiState as DetailsUiState.Success"
print "                                    if (state.isInWatchlist) {"
print "                                        viewModel.toggleWatchlist()"
print "                                    }"
print "                                    showBottomSheet = false"
print "                                } else {"
print "                                    showBottomSheet = false"
print "                                }"
print "                            }"
print "                            .padding(horizontal = 16.dp, vertical = 16.dp),"
print "                        verticalAlignment = Alignment.CenterVertically,"
print "                        horizontalArrangement = Arrangement.SpaceBetween"
print "                    ) {"
print "                        Text(text = text, color = TextPrimary, fontSize = 16.sp)"
print "                        Icon(icon, contentDescription = text, tint = TextPrimary)"
print "                    }"
print "                    if (text != \"مشاركة\") {"
print "                        HorizontalDivider(color = DarkGrey)"
print "                    }"
print "                }"
print "            }"
print "        }"
print "    }"
}
{ print }' app/src/main/java/com/example/ui/screens/details/DetailsScreen.kt > tmp_DetailsScreen.kt
mv tmp_DetailsScreen.kt app/src/main/java/com/example/ui/screens/details/DetailsScreen.kt
